name: School Meal Notification

on:
  schedule:
    - cron: '11 21 * * *'
    - cron: '11 2 * * *'
    - cron: '11 7 * * *'
    - cron: '11 14 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py requests

      - name: Run script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          TZ: Asia/Seoul
        run: python alarm.py
