name: API meal bot

on:
  schedule:
    - cron: '0 8 * * 5' # 매주 금요일 오전 08:00
    - cron: '0 8 1 * *' # 매월 1일 오전 08:00
  workflow_dispatch:

jobs:
  fetch-meal:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 파일 수정을 위한 권한

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Execute script
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py

      - name: Commit and Push changes
        id: git_commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .

          CHANGED_FILES=$(git diff --cached --name-only | tr '\n' ', ')
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update meal"
            git push
            echo "pushed=true" >> $GITHUB_OUTPUT

            echo "content<<EOF" >> $GITHUB_OUTPUT
            cat last.txt | head -n 1 >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "pushed=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Discord notification
        # 위 스텝에서 pushed가 true일 때만 실행
        if: steps.git_commit.outputs.pushed == 'true'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: success
          content: "🍱 식단 데이터가 업데이트되어 repository에 반영되었습니다!"
          title: "Meals Bot 알림"
          description: |
            **meals repo**: ${{ github.repository }}
            **updated month**: ${{ steps.git_commit.outputs.content }}