name: API meal bot

on:
  schedule:
    - cron: '0 8 * * 5' # 매주 금요일 오전 08:00
    - cron: '0 8 1 * *' # 매월 1일 오전 08:00
  workflow_dispatch:

jobs:
  fetch-meal:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 파일 수정을 위한 권한

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Execute script
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update meal" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
